---
swagger: '2.0'
info:
  title: os-console-output
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers/{server_id}/action":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    post:
      operationId: getConsoleOutput
      summary: Get console output for an instance
      description: |
        Gets console output for a server instance.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "output": "FAKE CONSOLE OUTPUT\nANOTHER\nLAST LINE"
              }
