---
swagger: '2.0'
info:
  title: os-consoles
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers/{server_id}/action":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    post:
      operationId: getConsole
      summary: Get console
      description: |
        Gets a console for a server instance.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples: {}
