---
swagger: '2.0'
info:
  title: os-coverage
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-coverage/action":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    post:
      operationId: stopReport
      summary: Stop coverage report
      description: |
        Stops coverage reporting.
      produces:
      - application/json
      responses:
        '202':
          description: 202 response
          examples:
            application/json: |-
              {
                  "path": "/tmp/tmpua9HvB/nova-coverage_rs2CaS"
              }
