---
swagger: '2.0'
info:
  title: os-ext-img-size
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/images/detail":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    get:
      operationId: listDetailImage
      summary: List details for images
      description: |
        Lists details for available images. Includes the image size.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "images": [
                      {
                          "status": "ACTIVE",
                          "updated": "2011-01-01T01:02:03Z",
                          "OS-EXT-IMG-SIZE:size": "74185822",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "bookmark"
                              },
                              {
                                  "href": "http://glance.openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "type": "application/vnd.openstack.image",
                                  "rel": "alternate"
                              }
                          ],
                          "created": "2011-01-01T01:02:03Z",
                          "minDisk": 0,
                          "name": "fakeimage7",
                          "progress": 100,
                          "minRam": 0,
                          "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                          "metadata": {
                              "auto_disk_config": "True",
                              "kernel_id": "nokernel",
                              "ramdisk_id": "nokernel",
                              "architecture": "x86_64"
                          }
                      },
                      {
                          "status": "ACTIVE",
                          "updated": "2011-01-01T01:02:03Z",
                          "OS-EXT-IMG-SIZE:size": "25165824",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/images/155d900f-4e14-4e4c-a73d-069cbf4541e6",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/images/155d900f-4e14-4e4c-a73d-069cbf4541e6",
                                  "rel": "bookmark"
                              },
                              {
                                  "href": "http://glance.openstack.example.com/openstack/images/155d900f-4e14-4e4c-a73d-069cbf4541e6",
                                  "type": "application/vnd.openstack.image",
                                  "rel": "alternate"
                              }
                          ],
                          "created": "2011-01-01T01:02:03Z",
                          "minDisk": 0,
                          "name": "fakeimage123456",
                          "progress": 100,
                          "minRam": 0,
                          "id": "155d900f-4e14-4e4c-a73d-069cbf4541e6",
                          "metadata": {
                              "kernel_id": "nokernel",
                              "ramdisk_id": "nokernel",
                              "architecture": "x86_64"
                          }
                      },
                      {
                          "status": "ACTIVE",
                          "updated": "2011-01-01T01:02:03Z",
                          "OS-EXT-IMG-SIZE:size": "58145823",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/images/a2459075-d96c-40d5-893e-577ff92e721c",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/images/a2459075-d96c-40d5-893e-577ff92e721c",
                                  "rel": "bookmark"
                              },
                              {
                                  "href": "http://glance.openstack.example.com/openstack/images/a2459075-d96c-40d5-893e-577ff92e721c",
                                  "type": "application/vnd.openstack.image",
                                  "rel": "alternate"
                              }
                          ],
                          "created": "2011-01-01T01:02:03Z",
                          "minDisk": 0,
                          "name": "fakeimage123456",
                          "progress": 100,
                          "minRam": 0,
                          "id": "a2459075-d96c-40d5-893e-577ff92e721c",
                          "metadata": {
                              "kernel_id": "nokernel",
                              "ramdisk_id": "nokernel"
                          }
                      },
                      {
                          "status": "ACTIVE",
                          "updated": "2011-01-01T01:02:03Z",
                          "OS-EXT-IMG-SIZE:size": "49163826",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/images/a440c04b-79fa-479c-bed1-0b816eaec379",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/images/a440c04b-79fa-479c-bed1-0b816eaec379",
                                  "rel": "bookmark"
                              },
                              {
                                  "href": "http://glance.openstack.example.com/openstack/images/a440c04b-79fa-479c-bed1-0b816eaec379",
                                  "type": "application/vnd.openstack.image",
                                  "rel": "alternate"
                              }
                          ],
                          "created": "2011-01-01T01:02:03Z",
                          "minDisk": 0,
                          "name": "fakeimage6",
                          "progress": 100,
                          "minRam": 0,
                          "id": "a440c04b-79fa-479c-bed1-0b816eaec379",
                          "metadata": {
                              "auto_disk_config": "False",
                              "kernel_id": "nokernel",
                              "ramdisk_id": "nokernel",
                              "architecture": "x86_64"
                          }
                      },
                      {
                          "status": "ACTIVE",
                          "updated": "2011-01-01T01:02:03Z",
                          "OS-EXT-IMG-SIZE:size": "26360814",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/images/c905cedb-7281-47e4-8a62-f26bc5fc4c77",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/images/c905cedb-7281-47e4-8a62-f26bc5fc4c77",
                                  "rel": "bookmark"
                              },
                              {
                                  "href": "http://glance.openstack.example.com/openstack/images/c905cedb-7281-47e4-8a62-f26bc5fc4c77",
                                  "type": "application/vnd.openstack.image",
                                  "rel": "alternate"
                              }
                          ],
                          "created": "2011-01-01T01:02:03Z",
                          "minDisk": 0,
                          "name": "fakeimage123456",
                          "progress": 100,
                          "minRam": 0,
                          "id": "c905cedb-7281-47e4-8a62-f26bc5fc4c77",
                          "metadata": {
                              "kernel_id": "155d900f-4e14-4e4c-a73d-069cbf4541e6",
                              "ramdisk_id": null
                          }
                      },
                      {
                          "status": "ACTIVE",
                          "updated": "2011-01-01T01:02:03Z",
                          "OS-EXT-IMG-SIZE:size": "84035174",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/images/cedef40a-ed67-4d10-800e-17455edce175",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/images/cedef40a-ed67-4d10-800e-17455edce175",
                                  "rel": "bookmark"
                              },
                              {
                                  "href": "http://glance.openstack.example.com/openstack/images/cedef40a-ed67-4d10-800e-17455edce175",
                                  "type": "application/vnd.openstack.image",
                                  "rel": "alternate"
                              }
                          ],
                          "created": "2011-01-01T01:02:03Z",
                          "minDisk": 0,
                          "name": "fakeimage123456",
                          "progress": 100,
                          "minRam": 0,
                          "id": "cedef40a-ed67-4d10-800e-17455edce175",
                          "metadata": {
                              "kernel_id": "nokernel",
                              "ramdisk_id": "nokernel"
                          }
                      },
                      {
                          "status": "ACTIVE",
                          "updated": "2011-01-01T01:02:03Z",
                          "OS-EXT-IMG-SIZE:size": "83594576",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/images/76fa36fc-c930-4bf3-8c8a-ea2a2420deb6",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/images/76fa36fc-c930-4bf3-8c8a-ea2a2420deb6",
                                  "rel": "bookmark"
                              },
                              {
                                  "href": "http://glance.openstack.example.com/openstack/images/76fa36fc-c930-4bf3-8c8a-ea2a2420deb6",
                                  "type": "application/vnd.openstack.image",
                                  "rel": "alternate"
                              }
                          ],
                          "created": "2011-01-01T01:02:03Z",
                          "minDisk": 0,
                          "name": "fakeimage123456",
                          "progress": 100,
                          "minRam": 0,
                          "id": "76fa36fc-c930-4bf3-8c8a-ea2a2420deb6",
                          "metadata": {
                              "kernel_id": "nokernel",
                              "ramdisk_id": "nokernel"
                          }
                      }
                  ]
              }
  "/v2/{tenant_id}/images/{image_id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: image_id
      required: true
      in: path
      type: string
      description: |
        Image ID stored through the image API. Typically a UUID.
    get:
      operationId: getImage
      summary: Get image details
      description: |
        Gets details for a specified image. Includes the image size.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "image": {
                      "status": "ACTIVE",
                      "updated": "2011-01-01T01:02:03Z",
                      "OS-EXT-IMG-SIZE:size": "74185822",
                      "links": [
                          {
                              "href": "http://openstack.example.com/v2/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                              "rel": "self"
                          },
                          {
                              "href": "http://openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                              "rel": "bookmark"
                          },
                          {
                              "href": "http://glance.openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                              "type": "application/vnd.openstack.image",
                              "rel": "alternate"
                          }
                      ],
                      "created": "2011-01-01T01:02:03Z",
                      "minDisk": 0,
                      "name": "fakeimage7",
                      "progress": 100,
                      "minRam": 0,
                      "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                      "metadata": {
                          "auto_disk_config": "True",
                          "kernel_id": "nokernel",
                          "ramdisk_id": "nokernel",
                          "architecture": "x86_64"
                      }
                  }
              }
