---
swagger: '2.0'
info:
  title: os-extended-availability-zone-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers/{server_id}":
    get:
      operationId: returndetails
      summary: Show server details
      description: |
        Shows details for a specified server.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "server": {
                      "status": "ACTIVE",
                      "updated": "2013-09-16T02:54:57Z",
                      "user_id": "fake",
                      "addresses": {
                          "private": [
                              {
                                  "version": 4,
                                  "type": "fixed",
                                  "addr": "192.168.0.3",
                                  "mac_addr": "aa:bb:cc:dd:ee:ff"
                              }
                          ]
                      },
                      "links": [
                          {
                              "href": "http://openstack.example.com/v3/servers/f22e4521-d03a-4e9f-9fd3-016b9e227219",
                              "rel": "self"
                          },
                          {
                              "href": "http://openstack.example.com/servers/f22e4521-d03a-4e9f-9fd3-016b9e227219",
                              "rel": "bookmark"
                          }
                      ],
                      "created": "2013-09-16T02:54:56Z",
                      "key_name": null,
                      "image": {
                          "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                          "links": [
                              {
                                  "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "name": "new-server-test",
                      "tenant_id": "openstack",
                      "os-extended-availability-zone:availability_zone": "nova",
                      "progress": 0,
                      "host_id": "b75d6736650f9b272223ceb48f4cde001de1856e381613a922117ab7",
                      "flavor": {
                          "id": "1",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/flavors/1",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "id": "f22e4521-d03a-4e9f-9fd3-016b9e227219",
                      "metadata": {
                          "My Server Name": "Apache1"
                      }
                  }
              }
  "/v2.1/servers/detail":
    get:
      operationId: returnlist
      summary: List server details for user
      description: |
        Lists server details for a specified user.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "servers": [
                      {
                          "status": "ACTIVE",
                          "updated": "2013-09-16T02:54:58Z",
                          "user_id": "fake",
                          "addresses": {
                              "private": [
                                  {
                                      "version": 4,
                                      "type": "fixed",
                                      "addr": "192.168.0.3",
                                      "mac_addr": "aa:bb:cc:dd:ee:ff"
                                  }
                              ]
                          },
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v3/servers/55f43fa2-dc7c-4c0b-b21a-76f9abe516f9",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/servers/55f43fa2-dc7c-4c0b-b21a-76f9abe516f9",
                                  "rel": "bookmark"
                              }
                          ],
                          "created": "2013-09-16T02:54:56Z",
                          "key_name": null,
                          "image": {
                              "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                              "links": [
                                  {
                                      "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "name": "new-server-test",
                          "tenant_id": "openstack",
                          "os-extended-availability-zone:availability_zone": "nova",
                          "progress": 0,
                          "host_id": "cf5540800371e53064a60b36ff9d6d1d6a8719ffc870c63a270c6bee",
                          "flavor": {
                              "id": "1",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/flavors/1",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "id": "55f43fa2-dc7c-4c0b-b21a-76f9abe516f9",
                          "metadata": {
                              "My Server Name": "Apache1"
                          }
                      }
                  ]
              }
