---
swagger: '2.0'
info:
  title: os-floating-ips
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-floating-ips":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the tenant or account.
    get:
      operationId: ListFloatingIPs
      summary: List floating IPs
      description: |
        Lists floating IP addresses associated with the tenant or account.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "floating_ips": [
                      {
                          "instance_id": null,
                          "ip": "10.10.10.1",
                          "fixed_ip": null,
                          "id": 1,
                          "pool": "nova"
                      },
                      {
                          "instance_id": null,
                          "ip": "10.10.10.2",
                          "fixed_ip": null,
                          "id": 2,
                          "pool": "nova"
                      }
                  ]
              }
    post:
      operationId: AllocateFloatingIP
      summary: Allocate floating IP
      description: |
        Allocates a new floating IP address to a tenant or account.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "floating_ip": {
                      "instance_id": null,
                      "ip": "10.10.10.1",
                      "fixed_ip": null,
                      "id": 1,
                      "pool": "nova"
                  }
              }
  "/v2/{tenant_id}/os-floating-ips/{id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the tenant or account.
    - name: id
      required: true
      in: path
      type: string
      description: |
        The unique identifier associated with allocated floating IP address.
    get:
      operationId: DetailFloatingIP
      summary: Show floating IP information
      description: |
        Shows information for a specified floating IP address.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "floating_ip": {
                      "instance_id": null,
                      "ip": "10.10.10.1",
                      "fixed_ip": null,
                      "id": 1,
                      "pool": "nova"
                  }
              }
    delete:
      operationId: DeallocateFloatingIP
      summary: Deallocate floating IP
      description: |
        Deallocates the floating IP address associated with floating\_IP\_address\_ID.
      produces: []
      responses:
        '202':
          description: 202 response
  "/v2/{tenant_id}/servers/{server_id}/action":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the tenant or account.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    post:
      operationId: RemoveFloatingIP
      summary: Remove floating IP
      description: |
        Removes a floating IP from an instance.
      produces: []
      responses:
        '202':
          description: 202 response
