---
swagger: '2.0'
info:
  title: os-hosts-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/os-hosts":
    get:
      operationId: listallhosts
      summary: List hosts
      description: |
        Lists hosts.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "hosts": [
                      {
                          "zone": "internal",
                          "host_name": "b6e4adbc193d428ea923899d07fb001e",
                          "service": "conductor"
                      },
                      {
                          "zone": "nova",
                          "host_name": "09c025b0efc64211bd23fc50fa974cdf",
                          "service": "compute"
                      },
                      {
                          "zone": "internal",
                          "host_name": "a942ebfa00064d9d89a9e5a175cb9ba8",
                          "service": "cert"
                      },
                      {
                          "zone": "internal",
                          "host_name": "e73ec0bd35c64de4a1adfa8b8969a1f6",
                          "service": "consoleauth"
                      },
                      {
                          "zone": "internal",
                          "host_name": "396a8a0a234f476eb05fb9fbc5802ba7",
                          "service": "network"
                      },
                      {
                          "zone": "internal",
                          "host_name": "abffda96592c4eacaf4111c28fddee17",
                          "service": "scheduler"
                      },
                      {
                          "zone": "internal",
                          "host_name": "a8820f04962a4b4ba9fe2e9540c24094",
                          "service": "cells"
                      }
                  ]
              }
  "/v2.1/os-hosts/{host_name}":
    put:
      operationId: enablehost
      summary: Enables host
      description: |
        Enables or puts a host in maintenance mode.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "host": {
                      "status": "enabled",
                      "maintenance_mode": "off_maintenance",
                      "host": "65c5d5b7e3bd44308e67fc50f362aee6"
                  }
              }
    get:
      operationId: showinfo
      summary: Show host details
      description: |
        Shows details for a specified host.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "host": [
                      {
                          "resource": {
                              "memory_mb": 8192,
                              "project": "(total)",
                              "host": "c1a7de0ac9d94e4baceae031d05caae3",
                              "cpu": 1,
                              "disk_gb": 1028
                          }
                      },
                      {
                          "resource": {
                              "memory_mb": 512,
                              "project": "(used_now)",
                              "host": "c1a7de0ac9d94e4baceae031d05caae3",
                              "cpu": 0,
                              "disk_gb": 0
                          }
                      },
                      {
                          "resource": {
                              "memory_mb": 0,
                              "project": "(used_max)",
                              "host": "c1a7de0ac9d94e4baceae031d05caae3",
                              "cpu": 0,
                              "disk_gb": 0
                          }
                      }
                  ]
              }
  "/v2.1/os-hosts/{host_name}/reboot":
    get:
      operationId: reboothost
      summary: Reboot host
      description: |
        Reboots a host.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "host": {
                      "host": "9557750dbc464741a89c907921c1cb31",
                      "power_action": "reboot"
                  }
              }
  "/v2.1/os-hosts/{host_name}/shutdown":
    get:
      operationId: shutdownhost
      summary: Shut down host
      description: |
        Shuts down a host.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "host": {
                      "host": "77cfa0002e4d45fe97f185968111b27b",
                      "power_action": "shutdown"
                  }
              }
  "/v2.1/os-hosts/{host_name}/startup":
    get:
      operationId: startshost
      summary: Start host
      description: |
        Starts a host.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "host": {
                      "host": "4b392b27930343bbaa27fd5d8328a564",
                      "power_action": "startup"
                  }
              }
