---
swagger: '2.0'
info:
  title: os-instance-actions
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers/{server_id}/os-instance-actions":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID of the server instance for which you want to list actions.
    get:
      operationId: listActions
      summary: List server actions
      description: |
        Lists history of successful actions for a specified server. Deployers set permissions for this request in the `policy.json` file. By default, all users can list actions.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "instanceActions": [
                      {
                          "instance_uuid": "b48316c5-71e8-45e4-9884-6c78055b9b13",
                          "user_id": "789",
                          "start_time": "2012-12-05 01:00:00.000000",
                          "request_id": "req-25517360-b757-47d3-be45-0e8d2a01b36a",
                          "action": "resize",
                          "message": "",
                          "project_id": "842"
                      },
                      {
                          "instance_uuid": "b48316c5-71e8-45e4-9884-6c78055b9b13",
                          "user_id": "789",
                          "start_time": "2012-12-05 00:00:00.000000",
                          "request_id": "req-3293a3f1-b44c-4609-b8d2-d81b105636b8",
                          "action": "reboot",
                          "message": "",
                          "project_id": "147"
                      }
                  ]
              }
  "/v2/{tenant_id}/servers/{server_id}/os-instance-actions/{action_id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID of the server instance for which you want to list actions.
    - name: action_id
      required: true
      in: path
      type: string
      description: |
        The UUID of the action for which you want to get details.
    get:
      operationId: getActionDetails
      summary: Get action details
      description: |
        Gets details for a specified action for a specified server instance. Deployers set permissions for this request in the `policy.json` file. By default, only administrators can get details for an action.
      produces:
      - application/json
      responses:
        '200':
          description: 200 203 response
          examples:
            application/json: |-
              {
                  "instanceAction": {
                      "instance_uuid": "b48316c5-71e8-45e4-9884-6c78055b9b13",
                      "user_id": "789",
                      "start_time": "2012-12-05 00:00:00.000000",
                      "request_id": "req-3293a3f1-b44c-4609-b8d2-d81b105636b8",
                      "action": "reboot",
                      "message": "",
                      "project_id": "147",
                      "events": [
                          {
                              "finish_time": "2012-12-05 01:02:00.000000",
                              "start_time": "2012-12-05 01:00:02.000000",
                              "traceback": "",
                              "event": "schedule",
                              "result": "Success"
                          },
                          {
                              "finish_time": "2012-12-05 01:04:00.000000",
                              "start_time": "2012-12-05 01:03:00.000000",
                              "traceback": "",
                              "event": "compute_create",
                              "result": "Success"
                          }
                      ]
                  }
              }
        '203':
          description: 200 203 response
          examples:
            application/json: |-
              {
                  "instanceAction": {
                      "instance_uuid": "b48316c5-71e8-45e4-9884-6c78055b9b13",
                      "user_id": "789",
                      "start_time": "2012-12-05 00:00:00.000000",
                      "request_id": "req-3293a3f1-b44c-4609-b8d2-d81b105636b8",
                      "action": "reboot",
                      "message": "",
                      "project_id": "147",
                      "events": [
                          {
                              "finish_time": "2012-12-05 01:02:00.000000",
                              "start_time": "2012-12-05 01:00:02.000000",
                              "traceback": "",
                              "event": "schedule",
                              "result": "Success"
                          },
                          {
                              "finish_time": "2012-12-05 01:04:00.000000",
                              "start_time": "2012-12-05 01:03:00.000000",
                              "traceback": "",
                              "event": "compute_create",
                              "result": "Success"
                          }
                      ]
                  }
              }
