---
swagger: '2.0'
info:
  title: os-instance-actions-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers/{server_id}/os-instance-actions":
    get:
      operationId: returnactionlist
      summary: List actions for an instance
      description: |
        Lists actions for a specified instance.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "instance_actions": [
                      {
                          "instance_uuid": "b48316c5-71e8-45e4-9884-6c78055b9b13",
                          "user_id": "789",
                          "start_time": "2012-12-05T01:00:00.000000",
                          "request_id": "req-25517360-b757-47d3-be45-0e8d2a01b36a",
                          "action": "resize",
                          "message": "",
                          "project_id": "842"
                      },
                      {
                          "instance_uuid": "b48316c5-71e8-45e4-9884-6c78055b9b13",
                          "user_id": "789",
                          "start_time": "2012-12-05T00:00:00.000000",
                          "request_id": "req-3293a3f1-b44c-4609-b8d2-d81b105636b8",
                          "action": "reboot",
                          "message": "",
                          "project_id": "147"
                      }
                  ]
              }
  "/v2.1/servers/{server_id}/os-instance-actions/{request_id}":
    get:
      operationId: returninstancedata
      summary: Shows instance action
      description: |
        Shows information about a specified instance action.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "instance_action": {
                      "instance_uuid": "b48316c5-71e8-45e4-9884-6c78055b9b13",
                      "user_id": "789",
                      "start_time": "2012-12-05T00:00:00.000000",
                      "request_id": "req-3293a3f1-b44c-4609-b8d2-d81b105636b8",
                      "action": "reboot",
                      "message": "",
                      "project_id": "147",
                      "events": [
                          {
                              "finish_time": "2012-12-05T01:02:00.000000",
                              "start_time": "2012-12-05T01:00:02.000000",
                              "traceback": "",
                              "event": "schedule",
                              "result": "Success"
                          },
                          {
                              "finish_time": "2012-12-05T01:04:00.000000",
                              "start_time": "2012-12-05T01:03:00.000000",
                              "traceback": "",
                              "event": "compute_create",
                              "result": "Success"
                          }
                      ]
                  }
              }
