---
swagger: '2.0'
info:
  title: os-keypairs
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-keypairs":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    get:
      operationId: getKeypair
      summary: List keypairs
      description: |
        Lists keypairs that are associated with the account.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "keypairs": [
                      {
                          "keypair": {
                              "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQC+Eo/RZRngaGTkFs7I62ZjsIlO79KklKbMXi8F+KITD4bVQHHn+kV+4gRgkgCRbdoDqoGfpaDFs877DYX9n4z6FrAIZ4PES8TNKhatifpn9NdQYWA+IkU8CuvlEKGuFpKRi/k7JLos/gHi2hy7QUwgtRvcefvD/vgQZOVw/mGR9Q== Generated by Nova\n",
                              "name": "keypair-601a2305-4f25-41ed-89c6-2a966fc8027a",
                              "fingerprint": "15:b0:f8:b3:f9:48:63:71:cf:7b:5b:38:6d:44:2d:4a"
                          }
                      }
                  ]
              }
    post:
      operationId: createKeypair
      summary: Create or import keypair
      description: |
        Generates or imports a keypair.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "keypair": {
                      "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDx8nkQv/zgGgB4rMYmIf+6A4l6Rr+o/6lHBQdW5aYd44bd8JttDCE/F/pNRr0lRE+PiqSPO8nDPHw0010JeMH9gYgnnFlyY3/OcJ02RhIPyyxYpv9FhY+2YiUkpwFOcLImyrxEsYXpD/0d3ac30bNH6Sw9JD9UZHYcpSxsIbECHw== Generated by Nova",
                      "user_id": "fake",
                      "name": "keypair-dab428fe-6186-4a14-b3de-92131f76cd39",
                      "fingerprint": "1e:2c:9b:56:79:4b:45:77:f9:ca:7a:98:2c:b0:d5:3c"
                  }
              }
  "/v2/{tenant_id}/os-keypairs/{keypair_name}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: keypair_name
      required: true
      in: path
      type: string
      description: |
        The name associated with a keypair.
    delete:
      operationId: deleteKeypair
      summary: Delete keypair
      description: |
        Deletes a keypair.
      produces: []
      responses:
        '202':
          description: 202 response
    get:
      operationId: showKeypair
      summary: Show keypair information
      description: |
        Shows a keypair associated with the account.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "keypair": {
                      "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDCSLxfzqB+e5yHdUSXvbxKkajjlfuhV+GArdseqPjfkKJ6no5echpin7dJp0FLXMJKxJZE3WWIRu25CQrJntmi7no27RkDfAGaTFbjz3DWY4A1HLeKAB5tFTwYQlr7CjMdoC/DY7UvKaatwLhH4Wvh5vMmXgF7AFzdkI28urwo+Q== nova@use03147k5-eth0\n",
                      "name": "hpdefault",
                      "fingerprint": "8b:2f:aa:b0:b8:97:dc:c8:50:aa:d4:8e:d0:34:61:d9"
                  }
              }
