---
swagger: '2.0'
info:
  title: os-networks-multi-provider-ext
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.0/networks":
    get:
      operationId: listMultiNetworks
      summary: List networks
      description: |
        Lists networks that are accessible to the tenant who submits the request. Networks with multiple segments include the `segments` list in the response.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "networks": [
                      {
                          "status": "ACTIVE",
                          "subnets": [],
                          "name": "net1",
                          "admin_state_up": true,
                          "tenant_id": "9bacb3c5d39d41a79512987f338cf177",
                          "segments": [
                              {
                                  "provider:network_type": "vlan",
                                  "provider:physical_network": "8bab8453-1bc9-45af-8c70-f83aa9b50453",
                                  "provider:segmentation_id": 2
                              },
                              {
                                  "provider:network_type": "stt",
                                  "provider:physical_network": "8bab8453-1bc9-45af-8c70-f83aa9b50453",
                                  "provider:segmentation_id": 0
                              }
                          ],
                          "router:external": false,
                          "port_security_enabled": true,
                          "shared": false,
                          "id": "4e8e5957-649f-477b-9e5b-f1f75b21c03c"
                      },
                      {
                          "status": "ACTIVE",
                          "subnets": [
                              "08eae331-0402-425a-923c-34f7cfe39c1b"
                          ],
                          "name": "private",
                          "provider:physical_network": null,
                          "admin_state_up": true,
                          "tenant_id": "26a7980765d0414dbc1fc1f88cdb7e6e",
                          "provider:network_type": "local",
                          "router:external": true,
                          "shared": true,
                          "id": "db193ab3-96e3-4cb3-8fc5-05f4296d0324",
                          "provider:segmentation_id": null
                      }
                  ]
              }
    post:
      operationId: createMultiNetwork
      summary: Create network with multiple segment mappings
      description: |
        Creates a network with multiple segment mappings.
      produces:
      - application/json
      responses:
        '201':
          description: 201 response
          examples:
            application/json: |-
              {
                  "network": {
                      "status": "ACTIVE",
                      "subnets": [],
                      "name": "net1",
                      "admin_state_up": true,
                      "tenant_id": "9bacb3c5d39d41a79512987f338cf177",
                      "segments": [
                          {
                              "provider:network_type": "vlan",
                              "provider:physical_network": "8bab8453-1bc9-45af-8c70-f83aa9b50453",
                              "provider:segmentation_id": 2
                          },
                          {
                              "provider:network_type": "stt",
                              "provider:physical_network": "8bab8453-1bc9-45af-8c70-f83aa9b50453",
                              "provider:segmentation_id": null
                          }
                      ],
                      "port_security_enabled": true,
                      "shared": false,
                      "id": "4e8e5957-649f-477b-9e5b-f1f75b21c03c"
                  }
              }
  "/v2.0/networks/{network_id}":
    parameters:
    - name: network_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the network of interest to you.
    get:
      operationId: showMultiNetwork
      summary: Show details for a network with multiple segments
      description: |
        Shows details for a specified network with multiple segments.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "network": {
                      "status": "ACTIVE",
                      "subnets": [],
                      "name": "net1",
                      "admin_state_up": true,
                      "tenant_id": "9bacb3c5d39d41a79512987f338cf177",
                      "segments": [
                          {
                              "provider:network_type": "vlan",
                              "provider:physical_network": "8bab8453-1bc9-45af-8c70-f83aa9b50453",
                              "provider:segmentation_id": 2
                          },
                          {
                              "provider:network_type": "stt",
                              "provider:physical_network": "8bab8453-1bc9-45af-8c70-f83aa9b50453",
                              "provider:segmentation_id": 0
                          }
                      ],
                      "router:external": false,
                      "port_security_enabled": true,
                      "shared": false,
                      "id": "4e8e5957-649f-477b-9e5b-f1f75b21c03c"
                  }
              }
