---
swagger: '2.0'
info:
  title: os-remote-consoles-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers/{server_id}/actions":
    post:
      operationId: getoutputvnc
      summary: Get console output
      description: |
        Gets text console output for VNC.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "console": {
                      "url": "http://127.0.0.1:6080/vnc_auto.html?token=191996c3-7b0f-42f3-95a7-f1839f2da6ed",
                      "type": "novnc"
                  }
              }
