---
swagger: '2.0'
info:
  title: os-subnets
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.0/subnets":
    get:
      operationId: listSubnets
      summary: List subnets
      description: |
        Lists subnets to which the specified tenant has access.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "subnets": [
                      {
                          "name": "private-subnet",
                          "enable_dhcp": true,
                          "network_id": "db193ab3-96e3-4cb3-8fc5-05f4296d0324",
                          "tenant_id": "26a7980765d0414dbc1fc1f88cdb7e6e",
                          "dns_nameservers": [],
                          "allocation_pools": [
                              {
                                  "start": "10.0.0.2",
                                  "end": "10.0.0.254"
                              }
                          ],
                          "host_routes": [],
                          "ip_version": 4,
                          "gateway_ip": "10.0.0.1",
                          "cidr": "10.0.0.0/24",
                          "id": "08eae331-0402-425a-923c-34f7cfe39c1b"
                      },
                      {
                          "name": "my_subnet",
                          "enable_dhcp": true,
                          "network_id": "d32019d3-bc6e-4319-9c1d-6722fc136a22",
                          "tenant_id": "4fd44f30292945e481c7b8a0c8908869",
                          "dns_nameservers": [],
                          "allocation_pools": [
                              {
                                  "start": "192.0.0.2",
                                  "end": "192.255.255.254"
                              }
                          ],
                          "host_routes": [],
                          "ip_version": 4,
                          "gateway_ip": "192.0.0.1",
                          "cidr": "192.0.0.0/8",
                          "id": "54d6f61d-db07-451c-9ab3-b9609b6b6f0b"
                      }
                  ]
              }
    post:
      operationId: bulkCreateSubnet
      summary: Bulk create subnet
      description: |
        Creates multiple subnets in a single request. Specify a list of subnets in the request body.
      produces:
      - application/json
      responses:
        '201':
          description: 201 response
          examples:
            application/json: |-
              {
                  "subnets": [
                      {
                          "name": "",
                          "enable_dhcp": true,
                          "network_id": "e6031bc2-901a-4c66-82da-f4c32ed89406",
                          "tenant_id": "d19231fc08ec4bc4829b668040d34512",
                          "dns_nameservers": [],
                          "allocation_pools": [
                              {
                                  "start": "192.168.199.2",
                                  "end": "192.168.199.254"
                              }
                          ],
                          "host_routes": [],
                          "ip_version": 4,
                          "gateway_ip": "192.168.199.1",
                          "cidr": "192.168.199.0/24",
                          "id": "0468a7a7-290d-4127-aedd-6c9449775a24"
                      },
                      {
                          "name": "",
                          "enable_dhcp": true,
                          "network_id": "64239a54-dcc4-4b39-920b-b37c2144effa",
                          "tenant_id": "d19231fc08ec4bc4829b668040d34512",
                          "dns_nameservers": [],
                          "allocation_pools": [
                              {
                                  "start": "10.56.4.2",
                                  "end": "10.56.7.254"
                              }
                          ],
                          "host_routes": [],
                          "ip_version": 4,
                          "gateway_ip": "10.56.4.1",
                          "cidr": "10.56.4.0/22",
                          "id": "b0e7435c-1512-45fb-aa9e-9a7c5932fb30"
                      }
                  ]
              }
  "/v2.0/subnets/{subnet_id}":
    parameters:
    - name: subnet_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the subnet of interest to you.
    get:
      operationId: showSubnet
      summary: Show subnet
      description: |
        Shows information for a specified subnet.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "subnet": {
                      "name": "my_subnet",
                      "enable_dhcp": true,
                      "network_id": "d32019d3-bc6e-4319-9c1d-6722fc136a22",
                      "tenant_id": "4fd44f30292945e481c7b8a0c8908869",
                      "dns_nameservers": [],
                      "allocation_pools": [
                          {
                              "start": "192.0.0.2",
                              "end": "192.255.255.254"
                          }
                      ],
                      "host_routes": [],
                      "ip_version": 4,
                      "gateway_ip": "192.0.0.1",
                      "cidr": "192.0.0.0/8",
                      "id": "54d6f61d-db07-451c-9ab3-b9609b6b6f0b"
                  }
              }
    put:
      operationId: updateSubnet
      summary: Update subnet
      description: |
        Updates a specified subnet.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "subnet": {
                      "name": "private-subnet",
                      "enable_dhcp": true,
                      "network_id": "db193ab3-96e3-4cb3-8fc5-05f4296d0324",
                      "tenant_id": "26a7980765d0414dbc1fc1f88cdb7e6e",
                      "dns_nameservers": [],
                      "allocation_pools": [
                          {
                              "start": "10.0.0.2",
                              "end": "10.0.0.254"
                          }
                      ],
                      "host_routes": [],
                      "ip_version": 4,
                      "gateway_ip": "10.0.0.1",
                      "cidr": "10.0.0.0/24",
                      "id": "08eae331-0402-425a-923c-34f7cfe39c1b"
                  }
              }
    delete:
      operationId: removeSubnet
      summary: Delete subnet
      description: |
        Deletes a specified subnet.
      produces: []
      responses:
        '204':
          description: 204 response
