---
swagger: '2.0'
info:
  title: os-volume-manage
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-volume-manage":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the tenant or account.
    post:
      operationId: manageExisting
      summary: Manage existing volume
      description: |
        Creates a Block Storage volume using existing storage instead of creating new storage.
      produces:
      - application/json
      responses:
        '202':
          description: 202 response
          examples:
            application/json: |-
              {
                  "volume": {
                      "status": "creating",
                      "size": 0,
                      "user_id": "eae1472b5fc5496998a3d06550929e7e",
                      "attachments": [],
                      "links": [
                          {
                              "href": "http://10.0.2.15:8776/v2/87c8522052ca4eed98bc672b4c1a3ddb/volumes/23cf872b-c781-4cd4-847d-5f2ec8cbd91c",
                              "rel": "self"
                          },
                          {
                              "href": "http://10.0.2.15:8776/87c8522052ca4eed98bc672b4c1a3ddb/volumes/23cf872b-c781-4cd4-847d-5f2ec8cbd91c",
                              "rel": "bookmark"
                          }
                      ],
                      "availability_zone": "az2",
                      "bootable": "false",
                      "encrypted": "false",
                      "created_at": "2014-07-18T00:12:54.000000",
                      "snapshot_id": null,
                      "volume_type": null,
                      "name": "New Volume",
                      "source_volid": null,
                      "os-vol-tenant-attr:tenant_id": "87c8522052ca4eed98bc672b4c1a3ddb",
                      "metadata": {
                          "key2": "value2",
                          "key1": "value1"
                      },
                      "id": "23cf872b-c781-4cd4-847d-5f2ec8cbd91c",
                      "description": "Volume imported from existingLV"
                  }
              }
