---
swagger: '2.0'
info:
  title: os-admin-actions
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers/{server_id}/action":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    post:
      operationId: addFloatingIP
      summary: Add floating IP address
      description: |
        Adds a floating IP address to an instance.
      produces: []
      responses:
        '200':
          description: 200 response
