---
swagger: '2.0'
info:
  title: os-agents
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-agents":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique ID of the tenant or account.
    get:
      operationId: listAgents
      summary: List agents
      description: |
        Lists all agent builds.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "agents": [
                      {
                          "url": "xxxxxxxxxxxx",
                          "hypervisor": "hypervisor",
                          "md5hash": "add6bb58e139be103324d04d82d8f545",
                          "version": "8.0",
                          "agent_id": "1",
                          "os": "os",
                          "architecture": "x86"
                      }
                  ]
              }
    post:
      operationId: createAgent
      summary: Create agent
      description: |
        Creates an agent build.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "agent": {
                      "url": "xxxxxxxxxxxx",
                      "hypervisor": "hypervisor",
                      "md5hash": "add6bb58e139be103324d04d82d8f545",
                      "version": "8.0",
                      "agent_id": "1",
                      "os": "os",
                      "architecture": "x86"
                  }
              }
    delete:
      operationId: deleteAgent
      summary: Delete agent
      description: |
        Deletes an existing agent build.
      produces: []
      responses:
        '202':
          description: 202 response
  "/v2/{tenant_id}/os-agents/{id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique ID of the tenant or account.
    - name: id
      required: true
      in: path
      type: string
      description: |
        The unique ID associated with the agent.
    put:
      operationId: updateAgent
      summary: Update agent
      description: |
        Updates an agent build.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "agent": {
                      "url": "xxx://xxxx/xxx/xxx",
                      "md5hash": "add6bb58e139be103324d04d82d8f545",
                      "agent_id": "1",
                      "version": "7.0"
                  }
              }
