---
swagger: '2.0'
info:
  title: os-config-drive-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers/{server_id}":
    get:
      operationId: returnserver
      summary: Show server details
      description: |
        Shows details for a specified server.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "server": {
                      "status": "ACTIVE",
                      "updated": "2013-09-22T02:33:25Z",
                      "user_id": "fake",
                      "addresses": {
                          "private": [
                              {
                                  "version": 4,
                                  "type": "fixed",
                                  "addr": "192.168.0.3",
                                  "mac_addr": "aa:bb:cc:dd:ee:ff"
                              }
                          ]
                      },
                      "links": [
                          {
                              "href": "http://openstack.example.com/v3/servers/7838ff1b-b71f-48b9-91e9-7c08de20b249",
                              "rel": "self"
                          },
                          {
                              "href": "http://openstack.example.com/servers/7838ff1b-b71f-48b9-91e9-7c08de20b249",
                              "rel": "bookmark"
                          }
                      ],
                      "created": "2013-09-22T02:33:23Z",
                      "key_name": null,
                      "image": {
                          "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                          "links": [
                              {
                                  "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "name": "new-server-test",
                      "tenant_id": "openstack",
                      "progress": 0,
                      "os-config-drive:config_drive": "",
                      "host_id": "1642bbdbd61a0f1c513b4bb6e418326103172698104bfa278eca106b",
                      "flavor": {
                          "id": "1",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/flavors/1",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "id": "7838ff1b-b71f-48b9-91e9-7c08de20b249",
                      "metadata": {
                          "My Server Name": "Apache1"
                      }
                  }
              }
  "/v2.1/servers/detail":
    get:
      operationId: returnlist
      summary: List server details for a user
      description: |
        Lists server details for a specified user.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "servers": [
                      {
                          "status": "ACTIVE",
                          "updated": "2013-09-22T02:33:19Z",
                          "user_id": "fake",
                          "addresses": {
                              "private": [
                                  {
                                      "version": 4,
                                      "type": "fixed",
                                      "addr": "192.168.0.3",
                                      "mac_addr": "aa:bb:cc:dd:ee:ff"
                                  }
                              ]
                          },
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v3/servers/f0318e69-11eb-4aed-9840-59b6c72beee8",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/servers/f0318e69-11eb-4aed-9840-59b6c72beee8",
                                  "rel": "bookmark"
                              }
                          ],
                          "created": "2013-09-22T02:33:17Z",
                          "key_name": null,
                          "image": {
                              "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                              "links": [
                                  {
                                      "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "name": "new-server-test",
                          "tenant_id": "openstack",
                          "progress": 0,
                          "os-config-drive:config_drive": "",
                          "host_id": "1ed067c90341cd9d94bbe5da960922b56f107262cdc75719a0d97b78",
                          "flavor": {
                              "id": "1",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/flavors/1",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "id": "f0318e69-11eb-4aed-9840-59b6c72beee8",
                          "metadata": {
                              "My Server Name": "Apache1"
                          }
                      }
                  ]
              }
