---
swagger: '2.0'
info:
  title: os-deferred-delete-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers/{server_id}/action":
    post:
      operationId: restoredelete
      summary: Restore deleted instance
      description: |
        Restores a previously deleted instance.
      produces: []
      responses:
        '202':
          description: 202 response
