---
swagger: '2.0'
info:
  title: os-extended-status-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers/{server_id}":
    get:
      operationId: returnserverdetails
      summary: Show server details
      description: |
        Shows details for a specified server.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "server": {
                      "status": "ACTIVE",
                      "updated": "2013-09-16T03:07:07Z",
                      "user_id": "fake",
                      "addresses": {
                          "private": [
                              {
                                  "version": 4,
                                  "type": "fixed",
                                  "addr": "192.168.0.3",
                                  "mac_addr": "aa:bb:cc:dd:ee:ff"
                              }
                          ]
                      },
                      "links": [
                          {
                              "href": "http://openstack.example.com/v3/servers/a868cb5e-c794-47bf-9cd8-e302b72bb94b",
                              "rel": "self"
                          },
                          {
                              "href": "http://openstack.example.com/servers/a868cb5e-c794-47bf-9cd8-e302b72bb94b",
                              "rel": "bookmark"
                          }
                      ],
                      "created": "2013-09-16T03:07:06Z",
                      "key_name": null,
                      "image": {
                          "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                          "links": [
                              {
                                  "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "os-extended-status:task_state": null,
                      "name": "new-server-test",
                      "os-extended-status:locked_by": null,
                      "progress": 0,
                      "os-extended-status:power_state": 1,
                      "os-extended-status:vm_state": "active",
                      "host_id": "46d2aa2d637bd55606304b611a1928627ee1278c149aef2206268d6e",
                      "flavor": {
                          "id": "1",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/flavors/1",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "id": "a868cb5e-c794-47bf-9cd8-e302b72bb94b",
                      "tenant_id": "openstack",
                      "metadata": {
                          "My Server Name": "Apache1"
                      }
                  }
              }
  "/v2.1/servers/detail":
    get:
      operationId: returnlistserver
      summary: List servers with details for user
      description: |
        Lists servers with details for a specified user.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "servers": [
                      {
                          "status": "ACTIVE",
                          "updated": "2013-09-16T03:07:10Z",
                          "user_id": "fake",
                          "addresses": {
                              "private": [
                                  {
                                      "version": 4,
                                      "type": "fixed",
                                      "addr": "192.168.0.3",
                                      "mac_addr": "aa:bb:cc:dd:ee:ff"
                                  }
                              ]
                          },
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v3/servers/6c8b5385-e74c-4fd5-add6-2fcf42d74a98",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/servers/6c8b5385-e74c-4fd5-add6-2fcf42d74a98",
                                  "rel": "bookmark"
                              }
                          ],
                          "created": "2013-09-16T03:07:09Z",
                          "key_name": null,
                          "image": {
                              "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                              "links": [
                                  {
                                      "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "os-extended-status:task_state": null,
                          "name": "new-server-test",
                          "os-extended-status:locked_by": null,
                          "progress": 0,
                          "os-extended-status:power_state": 1,
                          "os-extended-status:vm_state": "active",
                          "host_id": "a275e77473e464558c4aba0d68e1914d1164e7ee2f69affde7aaae2b",
                          "flavor": {
                              "id": "1",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/flavors/1",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "id": "6c8b5385-e74c-4fd5-add6-2fcf42d74a98",
                          "tenant_id": "openstack",
                          "metadata": {
                              "My Server Name": "Apache1"
                          }
                      }
                  ]
              }
