---
swagger: '2.0'
info:
  title: os-extended-server-attributes
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    get:
      operationId: extended_server_attributes_detail
      summary: List servers with extended server attributes
      description: |
        Lists detailed extended server attribute information for all servers.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "servers": [
                      {
                          "status": "ACTIVE",
                          "user_id": "fake",
                          "updated": "2012-11-15T19:27:05Z",
                          "hostId": "146245c049213a54b8c2352751518fcb4c2befd1b942b45a5a705d35",
                          "OS-EXT-SRV-ATTR:hypervisor_hostname": "fake-mini",
                          "addresses": {
                              "private": [
                                  {
                                      "version": 4,
                                      "addr": "192.168.0.3"
                                  }
                              ]
                          },
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v2/openstack/servers/e0c3563a-84ef-4d0b-bb80-23392cd23882",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/openstack/servers/e0c3563a-84ef-4d0b-bb80-23392cd23882",
                                  "rel": "bookmark"
                              }
                          ],
                          "created": "2012-11-15T19:27:05Z",
                          "tenant_id": "openstack",
                          "image": {
                              "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "name": "new-server-test",
                          "accessIPv4": "",
                          "accessIPv6": "",
                          "OS-EXT-SRV-ATTR:instance_name": "instance-00000001",
                          "progress": 0,
                          "OS-EXT-SRV-ATTR:host": "dd99797793774612b081a8be19bf721a",
                          "flavor": {
                              "id": "1",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/openstack/flavors/1",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "id": "e0c3563a-84ef-4d0b-bb80-23392cd23882",
                          "metadata": {
                              "My Server Name": "Apache1"
                          }
                      }
                  ]
              }
  "/v2/{tenant_id}/servers/{server_id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    get:
      operationId: extended_server_attributes_show
      summary: Show extended server attributes
      description: |
        Shows extended server attributes for a specified server.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "server": {
                      "status": "ACTIVE",
                      "user_id": "fake",
                      "updated": "2012-11-15T19:27:04Z",
                      "hostId": "2dfce43c41dd288cfac3a5b4251742b3bd2b37c12eb5927e757d9b4c",
                      "OS-EXT-SRV-ATTR:hypervisor_hostname": "fake-mini",
                      "addresses": {
                          "private": [
                              {
                                  "version": 4,
                                  "addr": "192.168.0.3"
                              }
                          ]
                      },
                      "links": [
                          {
                              "href": "http://openstack.example.com/v2/openstack/servers/1fc2392e-5727-46af-bc21-317a4a3eb04c",
                              "rel": "self"
                          },
                          {
                              "href": "http://openstack.example.com/openstack/servers/1fc2392e-5727-46af-bc21-317a4a3eb04c",
                              "rel": "bookmark"
                          }
                      ],
                      "created": "2012-11-15T19:27:04Z",
                      "tenant_id": "openstack",
                      "image": {
                          "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/openstack/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "name": "new-server-test",
                      "accessIPv4": "",
                      "accessIPv6": "",
                      "OS-EXT-SRV-ATTR:instance_name": "instance-00000001",
                      "progress": 0,
                      "OS-EXT-SRV-ATTR:host": "1169a68456af48238da47b1d5957a714",
                      "flavor": {
                          "id": "1",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/openstack/flavors/1",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "id": "1fc2392e-5727-46af-bc21-317a4a3eb04c",
                      "metadata": {
                          "My Server Name": "Apache1"
                      }
                  }
              }
