---
swagger: '2.0'
info:
  title: os-instance-usage-audit-log-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/os-instance-usage-audit-log":
    get:
      operationId: listusageaudits
      summary: List usage audits
      description: |
        Lists usage audits for a specified instance.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "instance_usage_audit_log": {
                      "total_errors": 0,
                      "num_hosts_running": 0,
                      "log": {},
                      "total_instances": 0,
                      "num_hosts_done": 0,
                      "num_hosts": 1,
                      "hosts_not_run": [
                          "defac351f91940668301096238d26b47"
                      ],
                      "overall_status": "0 of 1 hosts done. 0 errors.",
                      "period_ending": "2013-09-01 00:00:00",
                      "period_beginning": "2013-08-01 00:00:00",
                      "num_hosts_not_run": 1
                  }
              }
  "/v2.1/os-instance-usage-audit-log/{datetime}":
    parameters:
    - name: datetime
      required: true
      in: path
      type: string
      description: |
        The date and time stamp.
    get:
      operationId: listinstanceusage
      summary: List instance usage
      description: |
        Lists instance usage audits that occurred before a specified time.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "instance_usage_audit_log": {
                      "total_errors": 0,
                      "num_hosts_running": 0,
                      "log": {},
                      "total_instances": 0,
                      "num_hosts_done": 0,
                      "num_hosts": 1,
                      "hosts_not_run": [
                          "ccf86bf6d0104fe69ee658eaa31a7469"
                      ],
                      "overall_status": "0 of 1 hosts done. 0 errors.",
                      "period_ending": "2012-07-01 00:00:00",
                      "period_beginning": "2012-06-01 00:00:00",
                      "num_hosts_not_run": 1
                  }
              }
