---
swagger: '2.0'
info:
  title: os-interface
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers/{server_id}/os-interface":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    post:
      operationId: createAttachInterface
      summary: Create interface
      description: |
        Creates and uses a port interface to attach the port to a server instance.
      produces:
      - application/json
      responses:
        '202':
          description: 202 response
          examples:
            application/json: |-
              {
                  "interfaceAttachment": {
                      "port_id": "ce531f90-199f-48c0-816c-13e38010b442",
                      "port_state": "ACTIVE",
                      "fixed_ips": [
                          {
                              "subnet_id": "f8a6e8f8-c2ec-497c-9f23-da9616de54ef",
                              "ip_address": "192.168.1.1"
                          }
                      ],
                      "mac_addr": "fa:16:3e:4c:2c:30",
                      "net_id": "3cb9bc59-5699-4588-a4b1-b87f96708bc6"
                  }
              }
    get:
      operationId: listAttachedInterfaces
      summary: List interfaces
      description: |
        Lists port interfaces.
      produces:
      - application/json
      responses:
        '202':
          description: 202 response
          examples:
            application/json: |-
              {
                  "interfaceAttachments": [
                      {
                          "port_state": "ACTIVE",
                          "port_id": "ce531f90-199f-48c0-816c-13e38010b442",
                          "fixed_ips": [
                              {
                                  "subnet_id": "f8a6e8f8-c2ec-497c-9f23-da9616de54ef",
                                  "ip_address": "192.168.1.3"
                              }
                          ],
                          "net_id": "3cb9bc59-5699-4588-a4b1-b87f96708bc6",
                          "mac_addr": "fa:16:3e:4c:2c:30"
                      }
                  ]
              }
  "/v2/{tenant_id}/servers/{server_id}/os-interface/{attachment_id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    - name: attachment_id
      required: true
      in: path
      type: string
      description: |
        The interface ID.
    get:
      operationId: showAttachedInterface
      summary: Show attached interface information
      description: |
        Shows information about a specified port interface.
      produces:
      - application/json
      responses:
        '202':
          description: 202 response
          examples:
            application/json: |-
              {
                  "interfaceAttachment": {
                      "port_state": "ACTIVE",
                      "port_id": "ce531f90-199f-48c0-816c-13e38010b442",
                      "fixed_ips": [
                          {
                              "subnet_id": "f8a6e8f8-c2ec-497c-9f23-da9616de54ef",
                              "ip_address": "192.168.1.3"
                          }
                      ],
                      "net_id": "3cb9bc59-5699-4588-a4b1-b87f96708bc6",
                      "mac_addr": "fa:16:3e:4c:2c:30"
                  }
              }
    delete:
      operationId: deleteAttachedInterface
      summary: Detach interface
      description: |
        Detaches a specified port interface.
      produces: []
      responses:
        '202':
          description: 202 response
