---
swagger: '2.0'
info:
  title: os-limits
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/limits":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or project in a multi-tenancy cloud.
    get:
      operationId: showAbsoluteLimits
      summary: Show absolute limits
      description: |
        Shows absolute limits for a tenant.
      produces:
      - application/json
      responses:
        '200':
          description: 200 203 response
          examples:
            application/json: |-
              {
                  "limits": {
                      "rate": [],
                      "absolute": {
                          "totalSnapshotsUsed": 0,
                          "maxTotalVolumeGigabytes": 1000,
                          "maxTotalSnapshots": 10,
                          "totalVolumesUsed": 0,
                          "maxTotalVolumes": 10,
                          "totalGigabytesUsed": 0
                      }
                  }
              }
        '203':
          description: 200 203 response
          examples:
            application/json: |-
              {
                  "limits": {
                      "rate": [],
                      "absolute": {
                          "totalSnapshotsUsed": 0,
                          "maxTotalVolumeGigabytes": 1000,
                          "maxTotalSnapshots": 10,
                          "totalVolumesUsed": 0,
                          "maxTotalVolumes": 10,
                          "totalGigabytesUsed": 0
                      }
                  }
              }
