---
swagger: '2.0'
info:
  title: os-multinic-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers":
    post:
      operationId: removeip
      summary: Remove IP from instance
      description: |
        Removes an IP from a specified instance.
      produces: []
      responses:
        '202':
          description: 202 response
  "/v2.1/servers/action":
    post:
      operationId: addiptoinstance
      summary: Add IP to instance
      description: |
        Adds an IP to a specified network on an instance.
      produces: []
      responses:
        '202':
          description: 202 response
