---
swagger: '2.0'
info:
  title: os-multi-server-create
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    post:
      operationId: createServer
      summary: Create multiple servers
      description: |
        Creates one or more servers with an optional reservation ID.
      produces:
      - application/json
      responses:
        '202':
          description: 202 response
          examples:
            application/json: |-
              {
                  "reservation_id": "r-3fhpjulh"
              }
