---
swagger: '2.0'
info:
  title: os-migrations-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/os-migrations":
    get:
      operationId: returnmigrations
      summary: List migrations
      description: |
        Lists in-progress migrations.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "migrations": [
                      {
                          "dest_host": "1.2.3.4",
                          "instance_uuid": "instance_id_123",
                          "created_at": "2012-10-29T13:42:02.000000",
                          "source_node": "node1",
                          "updated_at": "2012-10-29T13:42:02.000000",
                          "dest_compute": "compute2",
                          "status": "Done",
                          "new_instance_type_id": 2,
                          "old_instance_type_id": 1,
                          "dest_node": "node2",
                          "id": 1234,
                          "source_compute": "compute1"
                      },
                      {
                          "dest_host": "5.6.7.8",
                          "instance_uuid": "instance_id_456",
                          "created_at": "2013-10-22T13:42:02.000000",
                          "source_node": "node10",
                          "updated_at": "2013-10-22T13:42:02.000000",
                          "dest_compute": "compute20",
                          "status": "Done",
                          "new_instance_type_id": 6,
                          "old_instance_type_id": 5,
                          "dest_node": "node20",
                          "id": 5678,
                          "source_compute": "compute10"
                      }
                  ]
              }
