---
swagger: '2.0'
info:
  title: os-ports-binding-ext
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.0/ports":
    get:
      operationId: listPorts
      summary: List ports
      description: |
        Lists ports to which the tenant has access.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "ports": [
                      {
                          "status": "ACTIVE",
                          "binding:host_id": "devstack",
                          "name": "",
                          "allowed_address_pairs": [],
                          "admin_state_up": true,
                          "network_id": "70c1db1f-b701-45bd-96e0-a313ee3430b3",
                          "tenant_id": "",
                          "extra_dhcp_opts": [],
                          "binding:vnic_type": "normal",
                          "binding:vif_type": "ovs",
                          "device_owner": "network:router_gateway",
                          "mac_address": "fa:16:3e:58:42:ed",
                          "id": "d80b1a3b-4fc1-49f3-952e-1e2ab7081d8b",
                          "binding:profile": {},
                          "fixed_ips": [
                              {
                                  "subnet_id": "008ba151-0b8c-4a67-98b5-0d2b87666062",
                                  "ip_address": "172.24.4.2"
                              }
                          ],
                          "binding:vif_details": {
                              "port_filter": true,
                              "ovs_hybrid_plug": true
                          },
                          "security_groups": [],
                          "device_id": "9ae135f4-b6e0-4dad-9e91-3c223e385824"
                      },
                      {
                          "status": "ACTIVE",
                          "binding:host_id": "devstack",
                          "name": "",
                          "allowed_address_pairs": [],
                          "admin_state_up": true,
                          "network_id": "f27aa545-cbdd-4907-b0c6-c9e8b039dcc2",
                          "tenant_id": "d397de8a63f341818f198abb0966f6f3",
                          "extra_dhcp_opts": [],
                          "binding:vnic_type": "normal",
                          "binding:vif_type": "ovs",
                          "device_owner": "network:router_interface",
                          "mac_address": "fa:16:3e:bb:3c:e4",
                          "id": "f71a6703-d6de-4be1-a91a-a570ede1d159",
                          "binding:profile": {},
                          "fixed_ips": [
                              {
                                  "subnet_id": "288bf4a1-51ba-43b6-9d0a-520e9005db17",
                                  "ip_address": "10.0.0.1"
                              }
                          ],
                          "binding:vif_details": {
                              "port_filter": true,
                              "ovs_hybrid_plug": true
                          },
                          "security_groups": [],
                          "device_id": "9ae135f4-b6e0-4dad-9e91-3c223e385824"
                      }
                  ]
              }
    post:
      operationId: createPort
      summary: Create port
      description: |
        Creates a port on the specified network.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "port": {
                      "status": "DOWN",
                      "binding:host_id": "",
                      "name": "private-port",
                      "allowed_address_pairs": [],
                      "admin_state_up": true,
                      "network_id": "a87cc70a-3e15-4acf-8205-9b711a3531b7",
                      "tenant_id": "d6700c0c9ffa4f1cb322cd4a1f3906fa",
                      "binding:vif_details": {},
                      "binding:vnic_type": "normal",
                      "binding:vif_type": "unbound",
                      "device_owner": "",
                      "mac_address": "fa:16:3e:c9:cb:f0",
                      "binding:profile": {},
                      "fixed_ips": [
                          {
                              "subnet_id": "a0304c3a-4f08-4c43-88af-d796509c97d2",
                              "ip_address": "10.0.0.2"
                          }
                      ],
                      "id": "65c0ee9f-d634-4522-8954-51021b570b0d",
                      "security_groups": [
                          "f0ac4394-7e4a-4409-9701-ba8be283dbc3"
                      ],
                      "device_id": ""
                  }
              }
  "/v2.0/ports/{port_id}":
    parameters:
    - name: port_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the port of interest to you.
    get:
      operationId: showPort
      summary: Show port
      description: |
        Shows information for the specified port.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "port": {
                      "status": "ACTIVE",
                      "binding:host_id": "devstack",
                      "name": "",
                      "allowed_address_pairs": [],
                      "admin_state_up": true,
                      "network_id": "a87cc70a-3e15-4acf-8205-9b711a3531b7",
                      "tenant_id": "7e02058126cc4950b75f9970368ba177",
                      "extra_dhcp_opts": [],
                      "binding:vnic_type": "normal",
                      "binding:vif_type": "ovs",
                      "device_owner": "network:router_interface",
                      "mac_address": "fa:16:3e:23:fd:d7",
                      "id": "46d4bfb9-b26e-41f3-bd2e-e6dcc1ccedb2",
                      "binding:profile": {},
                      "fixed_ips": [
                          {
                              "subnet_id": "a0304c3a-4f08-4c43-88af-d796509c97d2",
                              "ip_address": "10.0.0.1"
                          }
                      ],
                      "binding:vif_details": {
                          "port_filter": true,
                          "ovs_hybrid_plug": true
                      },
                      "security_groups": [],
                      "device_id": "5e3898d7-11be-483e-9732-b2f5eccd2b2e"
                  }
              }
    put:
      operationId: updatePort
      summary: Update port
      description: |
        Updates the specified port.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "port": {
                      "status": "DOWN",
                      "binding:host_id": "",
                      "name": "private-port",
                      "allowed_address_pairs": [],
                      "admin_state_up": true,
                      "network_id": "a87cc70a-3e15-4acf-8205-9b711a3531b7",
                      "tenant_id": "d6700c0c9ffa4f1cb322cd4a1f3906fa",
                      "binding:vif_details": {},
                      "binding:vnic_type": "normal",
                      "binding:vif_type": "unbound",
                      "device_owner": "",
                      "mac_address": "fa:16:3e:c9:cb:f0",
                      "binding:profile": {},
                      "fixed_ips": [
                          {
                              "subnet_id": "a0304c3a-4f08-4c43-88af-d796509c97d2",
                              "ip_address": "10.0.0.2"
                          }
                      ],
                      "id": "65c0ee9f-d634-4522-8954-51021b570b0d",
                      "security_groups": [
                          "f0ac4394-7e4a-4409-9701-ba8be283dbc3"
                      ],
                      "device_id": ""
                  }
              }
