---
swagger: '2.0'
info:
  title: os-server-start-stop
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/servers/{server_id}/action":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    post:
      operationId: stop
      summary: Stop server
      description: |
        Stops a running server and changes its status to STOPPED.
      produces: []
      responses:
        '202':
          description: 202 response
