---
swagger: '2.0'
info:
  title: os-security-groups
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-security-groups":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the tenant or account.
    get:
      operationId: listSecGroups
      summary: List security groups
      description: |
        Lists security groups.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_groups": [
                      {
                          "rules": [],
                          "tenant_id": "openstack",
                          "description": "default",
                          "name": "default",
                          "id": 1
                      }
                  ]
              }
    post:
      operationId: createSecGroup
      summary: Create security group
      description: |
        Creates a security group.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_group": {
                      "rules": [],
                      "tenant_id": "openstack",
                      "description": "description",
                      "name": "test",
                      "id": 2
                  }
              }
  "/v2/{tenant_id}/os-security-groups/servers/{server_id}/os-security-groups":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the tenant or account.
    - name: server_id
      required: true
      in: path
      type: string
      description: |
        The UUID for the server of interest to you.
    get:
      operationId: listSecGroupsByServer
      summary: List security groups by server
      description: |
        Lists security groups for a specified server.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_groups": [
                      {
                          "rules": [],
                          "tenant_id": "openstack",
                          "description": "default",
                          "name": "default",
                          "id": 1
                      }
                  ]
              }
  "/v2/{tenant_id}/os-security-groups/{security_group_id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the tenant or account.
    - name: security_group_id
      required: true
      in: path
      type: string
      description: |
        The unique identifier of the security group.
    get:
      operationId: showSecGroup
      summary: Show security group information
      description: |
        Shows information for a specified security group.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "security_group": {
                      "rules": [],
                      "tenant_id": "openstack",
                      "description": "default",
                      "name": "default",
                      "id": 1
                  }
              }
    delete:
      operationId: deleteSecGroup
      summary: Delete security group
      description: |
        Deletes a specified security group.
      produces: []
      responses:
        '202':
          description: 202 response
