---
swagger: '2.0'
info:
  title: os-server-usage-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2.1/servers/detail":
    get:
      operationId: returnserveruser
      summary: List server details for user
      description: |
        Lists server details for a specified user.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "servers": [
                      {
                          "status": "ACTIVE",
                          "updated": "2013-08-15T12:04:05Z",
                          "user_id": "fake",
                          "addresses": {
                              "private": [
                                  {
                                      "version": 4,
                                      "type": "fixed",
                                      "addr": "192.168.0.3",
                                      "mac_addr": "aa:bb:cc:dd:ee:ff"
                                  }
                              ]
                          },
                          "links": [
                              {
                                  "href": "http://openstack.example.com/v3/servers/ae114799-9164-48f5-a036-6ef9310acbc4",
                                  "rel": "self"
                              },
                              {
                                  "href": "http://openstack.example.com/servers/ae114799-9164-48f5-a036-6ef9310acbc4",
                                  "rel": "bookmark"
                              }
                          ],
                          "created": "2013-08-15T12:04:04Z",
                          "key_name": null,
                          "image": {
                              "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                              "links": [
                                  {
                                      "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "os-server-usage:launched_at": "2013-08-15T12:04:05.368766",
                          "name": "new-server-test",
                          "os-server-usage:terminated_at": null,
                          "tenant_id": "openstack",
                          "progress": 0,
                          "host_id": "117535ce0eda7ee02ebffe2c976173629385481ae3f2bded5e14a66b",
                          "flavor": {
                              "id": "1",
                              "links": [
                                  {
                                      "href": "http://openstack.example.com/flavors/1",
                                      "rel": "bookmark"
                                  }
                              ]
                          },
                          "id": "ae114799-9164-48f5-a036-6ef9310acbc4",
                          "metadata": {
                              "My Server Name": "Apache1"
                          }
                      }
                  ]
              }
  "/v2.1/servers/{server_id}":
    get:
      operationId: returnserverdetails
      summary: Show server details
      description: |
        Shows details for a specified server.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "server": {
                      "status": "ACTIVE",
                      "updated": "2013-08-15T08:12:40Z",
                      "user_id": "fake",
                      "addresses": {
                          "private": [
                              {
                                  "version": 4,
                                  "type": "fixed",
                                  "addr": "192.168.0.3",
                                  "mac_addr": "aa:bb:cc:dd:ee:ff"
                              }
                          ]
                      },
                      "links": [
                          {
                              "href": "http://openstack.example.com/v3/servers/cee6d136-e378-4cfc-9eec-71797f025991",
                              "rel": "self"
                          },
                          {
                              "href": "http://openstack.example.com/servers/cee6d136-e378-4cfc-9eec-71797f025991",
                              "rel": "bookmark"
                          }
                      ],
                      "created": "2013-08-15T08:12:40Z",
                      "key_name": null,
                      "image": {
                          "id": "70a599e0-31e7-49b7-b260-868f441e862b",
                          "links": [
                              {
                                  "href": "http://glance.openstack.example.com/images/70a599e0-31e7-49b7-b260-868f441e862b",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "os-server-usage:launched_at": "2013-08-15T08:12:40.108903",
                      "name": "new-server-test",
                      "os-server-usage:terminated_at": null,
                      "tenant_id": "openstack",
                      "progress": 0,
                      "host_id": "73cf3a40601b63f5992894be2daa3712dd599d1c919984951e21edda",
                      "flavor": {
                          "id": "1",
                          "links": [
                              {
                                  "href": "http://openstack.example.com/flavors/1",
                                  "rel": "bookmark"
                              }
                          ]
                      },
                      "id": "cee6d136-e378-4cfc-9eec-71797f025991",
                      "metadata": {
                          "My Server Name": "Apache1"
                      }
                  }
              }
