---
swagger: '2.0'
info:
  title: os-services
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/os-services":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    get:
      operationId: listServices
      summary: List services
      description: |
        Lists running services.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "services": [
                      {
                          "status": "disabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:02.000000",
                          "host": "host1"
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:05.000000",
                          "host": "host1"
                      },
                      {
                          "status": "enabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "down",
                          "updated_at": "2012-09-19T06:55:34.000000",
                          "host": "host2"
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "down",
                          "updated_at": "2012-09-18T08:03:38.000000",
                          "host": "host2"
                      }
                  ]
              }
  "/v2/{tenant_id}/os-services/enable":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    put:
      operationId: enableScheduling
      summary: Enable scheduling for a service
      description: |
        Enables scheduling for a service.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "service": {
                      "status": "enabled",
                      "binary": "nova-compute",
                      "host": "host1"
                  }
              }
  "/v2/{tenant_id}/os-services/disable":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    put:
      operationId: disableScheduling
      summary: Disable scheduling for a service
      description: |
        Disables scheduling for a service.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "service": {
                      "status": "disabled",
                      "binary": "nova-compute",
                      "host": "host1"
                  }
              }
  "/v2/{tenant_id}/os-services/disable-log-reason":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    put:
      operationId: disableLogReason
      summary: Log disabled service information
      description: |
        Logs information to the service table about why a service was disabled.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "service": {
                      "status": "disabled",
                      "binary": "nova-compute",
                      "host": "host1",
                      "disabled_reason": "test2"
                  }
              }
  "/v2/{tenant_id}/os-services/detail":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    get:
      operationId: getDisableReasonDetail
      summary: List disabled services
      description: |
        Lists disabled services. If information exists, includes reasons why services were disabled.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "services": [
                      {
                          "status": "disabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:02.000000",
                          "host": "host1",
                          "disabled_reason": "test1"
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "up",
                          "updated_at": "2012-10-29T13:42:05.000000",
                          "host": "host1",
                          "disabled_reason": "test2"
                      },
                      {
                          "status": "enabled",
                          "binary": "nova-scheduler",
                          "zone": "internal",
                          "state": "down",
                          "updated_at": "2012-09-19T06:55:34.000000",
                          "host": "host2",
                          "disabled_reason": ""
                      },
                      {
                          "status": "disabled",
                          "binary": "nova-compute",
                          "zone": "nova",
                          "state": "down",
                          "updated_at": "2012-09-18T08:03:38.000000",
                          "host": "host2",
                          "disabled_reason": "test4"
                      }
                  ]
              }
