---
swagger: '2.0'
info:
  title: os-used-limits-for-admins
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/v2/{tenant_id}/limits/{tenant_id}":
    parameters:
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant or account in a multi-tenancy cloud.
    - name: tenant_id
      required: true
      in: path
      type: string
      description: |
        The ID for the tenant for which an administrator wants to get quota information. Specify the customer tenant ID in the URI as `tenant_id={tenant_id}`.
    get:
      operationId: getCustomerLimits
      summary: Get customer limits
      description: |
        Enables administrators to get absolute and rate limit information, including information about currently used absolute limits, for a specified customer tenant ID.
      produces:
      - application/json
      responses:
        '200':
          description: 200 response
          examples:
            application/json: |-
              {
                  "limits": {
                      "rate": [
                          {
                              "regex": ".*",
                              "limit": [
                                  {
                                      "value": 120,
                                      "verb": "POST",
                                      "next-available": "2012-11-27T17:24:52Z",
                                      "remaining": 120,
                                      "unit": "MINUTE"
                                  },
                                  {
                                      "value": 120,
                                      "verb": "PUT",
                                      "next-available": "2012-11-27T17:24:52Z",
                                      "remaining": 120,
                                      "unit": "MINUTE"
                                  },
                                  {
                                      "value": 120,
                                      "verb": "DELETE",
                                      "next-available": "2012-11-27T17:24:52Z",
                                      "remaining": 120,
                                      "unit": "MINUTE"
                                  }
                              ],
                              "uri": "*"
                          },
                          {
                              "regex": "^/servers",
                              "limit": [
                                  {
                                      "value": 120,
                                      "verb": "POST",
                                      "next-available": "2012-11-27T17:24:52Z",
                                      "remaining": 120,
                                      "unit": "MINUTE"
                                  }
                              ],
                              "uri": "*/servers"
                          },
                          {
                              "regex": ".*changes-since.*",
                              "limit": [
                                  {
                                      "value": 120,
                                      "verb": "GET",
                                      "next-available": "2012-11-27T17:24:52Z",
                                      "remaining": 120,
                                      "unit": "MINUTE"
                                  }
                              ],
                              "uri": "*changes-since*"
                          },
                          {
                              "regex": "^/os-fping",
                              "limit": [
                                  {
                                      "value": 12,
                                      "verb": "GET",
                                      "next-available": "2012-11-27T17:24:52Z",
                                      "remaining": 12,
                                      "unit": "MINUTE"
                                  }
                              ],
                              "uri": "*/os-fping"
                          }
                      ],
                      "absolute": {
                          "maxServerMeta": 128,
                          "maxPersonality": 5,
                          "maxImageMeta": 128,
                          "maxPersonalitySize": 10240,
                          "maxTotalRAMSize": 51200,
                          "maxSecurityGroupRules": 20,
                          "maxTotalKeypairs": 100,
                          "totalCoresUsed": 0,
                          "totalRAMUsed": 0,
                          "maxSecurityGroups": 10,
                          "totalFloatingIpsUsed": 0,
                          "totalInstancesUsed": 0,
                          "totalSecurityGroupsUsed": 0,
                          "maxTotalFloatingIps": 10,
                          "maxTotalInstances": 10,
                          "maxTotalCores": 20
                      }
                  }
              }
