---
swagger: '2.0'
info:
  title: os-versions-v2.1
  version: Unknown
consumes:
- application/json
produces:
- application/json
paths:
  "/":
    get:
      operationId: listVersionsv2.1
      summary: List API versions
      description: |
        Lists information about all Compute API versions.
      produces:
      - application/json
      responses:
        '200':
          description: 200 300 response
          examples:
            application/json: |-
              {
                  "versions": [
                      {
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z",
                          "id": "v2.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v2/",
                                  "rel": "self"
                              }
                          ]
                      },
                      {
                          "status": "EXPERIMENTAL",
                          "updated": "2013-07-23T11:33:21Z",
                          "id": "v3.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v3/",
                                  "rel": "self"
                              }
                          ]
                      }
                  ]
              }
        '300':
          description: 200 300 response
          examples:
            application/json: |-
              {
                  "versions": [
                      {
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z",
                          "id": "v2.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v2/",
                                  "rel": "self"
                              }
                          ]
                      },
                      {
                          "status": "EXPERIMENTAL",
                          "updated": "2013-07-23T11:33:21Z",
                          "id": "v3.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v3/",
                                  "rel": "self"
                              }
                          ]
                      }
                  ]
              }
  "/v2.1":
    get:
      operationId: showVersionDetailsv2.1
      summary: Show API v2.1 details
      description: |
        Shows details for Compute API v2.1.
      produces:
      - application/json
      responses:
        '200':
          description: 200 203 response
          examples:
            application/json: |-
              {
                  "versions": [
                      {
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z",
                          "id": "v2.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v2/",
                                  "rel": "self"
                              }
                          ]
                      },
                      {
                          "status": "EXPERIMENTAL",
                          "updated": "2013-07-23T11:33:21Z",
                          "id": "v3.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v3/",
                                  "rel": "self"
                              }
                          ]
                      }
                  ]
              }
        '203':
          description: 200 203 response
          examples:
            application/json: |-
              {
                  "versions": [
                      {
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z",
                          "id": "v2.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v2/",
                                  "rel": "self"
                              }
                          ]
                      },
                      {
                          "status": "EXPERIMENTAL",
                          "updated": "2013-07-23T11:33:21Z",
                          "id": "v3.0",
                          "links": [
                              {
                                  "href": "http://23.253.228.211:8774/v3/",
                                  "rel": "self"
                              }
                          ]
                      }
                  ]
              }
